GET http://localhost:8080/api/channels/30
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTVEMiLCJVU0VSTkFNRSI6ImJhYm9vdG90byIsIlVTRVJfUk9MRSI6IlJPTEVfVVNFUiJ9.oF-cpY1ZdjCTo8fyK0C9UPy11kMUYYBLO0cj_ge1Vvc

###