###################################################################################
# Local 환경
---
server:
  port: 8090

spring:
  profiles: local

  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@121.124.124.40:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: stc_mdr
    password: STC_MDR

  security:
    user:
      name: user
      password: 1234

mybatis:
  type-aliases-package: com.stc.sns.visualization.mybatis.domain
  mapper-locations: mapper/**/*Mapper.xml

logging:
  file: D:\usr\local\stc-service\logs


###################################################################################
# Real 환경
---
server:
  port: 8090

spring:
  profiles: real

  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@175.207.12.220:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: SNS_USER
    password: STC0501

  security:
    user:
      name: user
      password: 1234

mybatis:
  type-aliases-package: com.stc.sns.visualization.mybatis.domain
  mapperlocations: mapper/**/*Mapper.xml

logging:
  file: \usr\local\stc-service\logs
