
###################################################################################
# 공통 설정

server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      suffix: .log
      prefix: stc_api_access_log
      file-date-format: yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b"
      directory: /usr/local/stc-service/logs

logging:
  file: /usr/local/stc-service/logs
  level:
    com.stc.sns.visualization: info
    org.hibernate: debug

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true


mybatis:
  type-aliases-package: com.stc.sns.visualization.mybatis.domain
  mapperlocations: mapper/**/*Mapper.xml

###################################################################################
# Local 환경
---
server:
  port: 11422
  tomcat:
    accesslog:
      directory: D:\usr\local\stc-service\logs

spring:
  profiles: local

  jpa:
    hibernate.ddl-auto: validate

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@121.124.124.40:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: stc_mdr
    password: STC_MDR
    tomcat:
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 180000

  security:
    user:
      name: user
      password: 1234

logging:
  file: D:\usr\local\stc-service\logs


###################################################################################
# Local 환경
---
server:
  port: 11422
  tomcat:
    accesslog:
      directory: D:\usr\local\stc-service\logs

spring:
  profiles: local-live

  jpa:
    hibernate.ddl-auto: validate

  datasource:
    hikari:
      connection-timeout: 30000
      validation-timeout: 10000
    url: jdbc:log4jdbc:oracle:thin:@175.207.12.220:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: SNS_USER
    password: STC0501
    tomcat:
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 180000

  security:
    user:
      name: user
      password: 1234

logging:
  file: D:\usr\local\stc-service\logs


###################################################################################
# Real 환경
---
server:
  port: 11422

spring:
  profiles: real-mcst

  jpa:
    hibernate.ddl-auto: validate

  datasource:
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
    url: jdbc:log4jdbc:oracle:thin:@175.207.12.220:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: SNS_USER
    password: STC0501
    tomcat:
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 180000


  security:
    user:
      name: user
      password: 1234

logging:
  file: D:\stc-sns-service\logs


###################################################################################
# Real 환경
---
server:
  port: 11422
  ssl:
    enabled: true
    key-store: /usr/local/stc/ssl/keystore
    key-alias: alias
    key-store-password: "!4416stc"

spring:
  profiles: real

  jpa:
    hibernate.ddl-auto: validate

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@175.207.12.220:1521:ORCL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: SNS_USER
    password: STC0501

  security:
    user:
      name: user
      password: 1234

logging:
  file: /usr/local/stc-service/logs